#include <pebble.h>
#include "gbitmap_color_palette_manipulator.h"

#define SHOW_APP_LOGS

static Window *s_main_window;
static AppTimer *app_timer;

// Configuration parameters.
#define KEY_TIMEBACKGROUND 0
#define KEY_TIMEFOREGROUND 1
#define KEY_DATEBACKGROUND 2
#define KEY_DATEFOREGROUND 3
#define KEY_DATETIMEOUT 4

// Slot on-screen layout:
//     0 1
//     2 3
#define TOTAL_IMAGE_SLOTS 4
#define NUMBER_OF_IMAGES 10

// These images are 72 x 84 pixels (i.e. a quarter of the Aplite display),
// black and white with the digit character centered in the image.
// (As generated by the `fonttools/font2png.py` script.)
const int IMAGE_RESOURCE_IDS[NUMBER_OF_IMAGES] = {
  RESOURCE_ID_IMAGE_NUM_0, RESOURCE_ID_IMAGE_NUM_1, RESOURCE_ID_IMAGE_NUM_2,
  RESOURCE_ID_IMAGE_NUM_3, RESOURCE_ID_IMAGE_NUM_4, RESOURCE_ID_IMAGE_NUM_5,
  RESOURCE_ID_IMAGE_NUM_6, RESOURCE_ID_IMAGE_NUM_7, RESOURCE_ID_IMAGE_NUM_8,
  RESOURCE_ID_IMAGE_NUM_9
};

static GBitmap *s_images[TOTAL_IMAGE_SLOTS + 1];
static BitmapLayer *s_image_layers[TOTAL_IMAGE_SLOTS];

#define EMPTY_SLOT -1

// The state is either "empty" or the digit of the image currently in the slot.
static int s_image_slot_state[TOTAL_IMAGE_SLOTS] = {
  EMPTY_SLOT, EMPTY_SLOT, EMPTY_SLOT, EMPTY_SLOT
};

// Loads the digit image from the application's resources and
// displays it on-screen in the correct location.
// Each slot is a quarter of the screen.
static void load_digit_image_into_slot(int slot_number, int digit_value, int foreground_colour, int background_colour) {

  GRect bounds = layer_get_bounds(window_get_root_layer(s_main_window));

  s_image_slot_state[slot_number] = digit_value;
  s_images[slot_number] = gbitmap_create_with_resource(IMAGE_RESOURCE_IDS[digit_value]);

  // If requested background is white then replace the existing white digit with a red placeholder, replace
  // the black background with white, and then replace the red placeholder with the requested colour.
  // Note: use the gbitmap_fill_all_except first to get rid of any stray colours.
  if(gcolor_equal(GColorFromHEX(background_colour), GColorWhite)) {
      gbitmap_fill_all_except(GColorBlack, GColorRed, false, s_images[slot_number], NULL);
      replace_gbitmap_color(GColorBlack, GColorWhite, s_images[slot_number], NULL);
      replace_gbitmap_color(GColorRed, GColorFromHEX(foreground_colour), s_images[slot_number], NULL);
  }
  // Requested foreground is black then replace the existing black background with a red placeholder, replace
  // the white digit with black, and then replace the red placeholder with the requested colour.
  else if(gcolor_equal(GColorFromHEX(foreground_colour), GColorBlack)) {
      gbitmap_fill_all_except(GColorWhite, GColorRed, false, s_images[slot_number], NULL);
      replace_gbitmap_color(GColorWhite, GColorBlack, s_images[slot_number], NULL);
      replace_gbitmap_color(GColorRed, GColorFromHEX(background_colour), s_images[slot_number], NULL);
  }
  // Replace the black background with the requested background and the white digit with the requested foreground.
  else {
      gbitmap_fill_all_except(GColorWhite, GColorFromHEX(background_colour), false, s_images[slot_number], NULL);
      replace_gbitmap_color(GColorWhite, GColorFromHEX(foreground_colour), s_images[slot_number], NULL);
  }
  
  GRect tile_bounds = gbitmap_get_bounds(s_images[slot_number]);

  const int x_offset = (bounds.size.w - (2 * tile_bounds.size.w)) / 2;
  const int y_offset = (bounds.size.h - (2 * tile_bounds.size.h)) / 2;
  BitmapLayer *bitmap_layer = bitmap_layer_create(
    GRect(x_offset + ((slot_number % 2) * tile_bounds.size.w),
      y_offset + ((slot_number / 2) * tile_bounds.size.h),
      tile_bounds.size.w, tile_bounds.size.h));
  s_image_layers[slot_number] = bitmap_layer;
  bitmap_layer_set_bitmap(bitmap_layer, s_images[slot_number]);

  Layer *window_layer = window_get_root_layer(s_main_window);
  layer_add_child(window_layer, bitmap_layer_get_layer(bitmap_layer));
}

static void unload_digit_image_from_slot(int slot_number) {
  if (s_image_slot_state[slot_number] != EMPTY_SLOT) {
    layer_remove_from_parent(bitmap_layer_get_layer(s_image_layers[slot_number]));
    bitmap_layer_destroy(s_image_layers[slot_number]);
    gbitmap_destroy(s_images[slot_number]);

    // This is now an empty slot
    s_image_slot_state[slot_number] = EMPTY_SLOT;
  }
}

static void display_value(unsigned short value, unsigned short row_number, bool show_first_leading_zero, bool isdate) {

  int foreground_colour;
  int background_colour;

  // Get the colours of the displayed values.
  if(isdate) {
    if(!(background_colour = persist_read_int(KEY_DATEBACKGROUND))) {
        // There was no saved preference so set a default of black.
        background_colour = 0x000000;
    }
    if(!(foreground_colour = persist_read_int(KEY_DATEFOREGROUND))) {
        // There was no saved preference so set a default white.
        foreground_colour = 0xFFFFFF;
    }
  }
  else {
    if(!(background_colour = persist_read_int(KEY_TIMEBACKGROUND))) {
        // There was no saved preference so set a default of white.
        background_colour = 0xFFFFFF;
    }
    if(!(foreground_colour = persist_read_int(KEY_TIMEFOREGROUND))) {
        // There was no saved preference so set a default of black.
        foreground_colour = 0x000000;
    }
  }

  value = value % 100; // Maximum of two digits per row.

  // Column order is: | Column 0 | Column 1 |
  // (We process the columns in reverse order because that makes
  // extracting the digits from the value easier.)
  for (int column_number = 1; column_number >= 0; column_number--) {
    int slot_number = (row_number * 2) + column_number;
    unload_digit_image_from_slot(slot_number);
    if (!((value == 0) && (column_number == 0) && !show_first_leading_zero)) {
      load_digit_image_into_slot(slot_number, value % 10, foreground_colour, background_colour);
    }
    value = value / 10;
  }
}

static unsigned short get_display_hour(unsigned short hour) {
  if (clock_is_24h_style()) {
    return hour;
  }
  // Converts "0" to "12"
  unsigned short display_hour = hour % 12;
  return display_hour ? display_hour : 12;
}

static void display_time(struct tm *disp_time) {
  display_value(get_display_hour(disp_time->tm_hour), 0, false, false);
  display_value(disp_time->tm_min, 1, true, false);
}

static void tick_handler(struct tm *tick_time, TimeUnits units_changed) {
  #ifdef SHOW_APP_LOGS
  APP_LOG(APP_LOG_LEVEL_DEBUG, "%d:%d", tick_time->tm_hour, tick_time->tm_min);
  #endif
  display_time(tick_time);
}

static void auto_redisplay_time(void *data) {
  time_t now = time(NULL);
  struct tm tick_time = *localtime(&now); 
  app_timer = NULL;
  display_time(&tick_time);
}

static void display_date(struct tm *disp_date) {
  int datetimeout = 1;

  display_value(disp_date->tm_mday, 0, true, true);
  display_value(disp_date->tm_mon+1, 1, true, true);
  if (app_timer != NULL) {
    app_timer_cancel(app_timer);
  }

  // Get the requested timeout value if it exists.
  if(!(datetimeout = persist_read_int(KEY_DATETIMEOUT))) {
      // There was no saved preference so set a default of 1 second.
      datetimeout = 1;
  }

  #ifdef SHOW_APP_LOGS
  APP_LOG(APP_LOG_LEVEL_DEBUG, "%d, %d", datetimeout, datetimeout * 1000);
  #endif

  app_timer = app_timer_register(datetimeout * 1000, auto_redisplay_time, NULL);
}

static void tap_handler(AccelAxisType axis, int32_t direction) {
  // Date requested so get the current date.
  time_t now = time(NULL);
  struct tm tick_date = *localtime(&now); 
  #ifdef SHOW_APP_LOGS
  APP_LOG(APP_LOG_LEVEL_DEBUG, "%d/%d", tick_date.tm_mday, tick_date.tm_mon+1);
  #endif
  app_timer = NULL;
  display_date(&tick_date);
}

static void main_window_load(Window *window) {
  time_t now = time(NULL);
  struct tm tick_time = *localtime(&now);  // First run through so set display_time.
  display_time(&tick_time);
}

static void main_window_unload(Window *window) {
  for (int i = 0; i < TOTAL_IMAGE_SLOTS; i++) {
    unload_digit_image_from_slot(i);
  }
}

static void inbox_received_handler(DictionaryIterator *iter, void *context) {
  Tuple *timebackground_t = dict_find(iter, KEY_TIMEBACKGROUND);
  Tuple *timeforeground_t = dict_find(iter, KEY_TIMEFOREGROUND);
  Tuple *datebackground_t = dict_find(iter, KEY_DATEBACKGROUND);
  Tuple *dateforeground_t = dict_find(iter, KEY_DATEFOREGROUND);
  Tuple *datetimeout_t = dict_find(iter, KEY_DATETIMEOUT);

  // Retrieve the values passed in and store them in persistent storage.
  if (timebackground_t) {
    persist_write_int(KEY_TIMEBACKGROUND, timebackground_t->value->int32);
  }

  if (timeforeground_t) {
    persist_write_int(KEY_TIMEFOREGROUND, timeforeground_t->value->int32);
  }

  if (datebackground_t) {
    persist_write_int(KEY_DATEBACKGROUND, datebackground_t->value->int32);
  }

  if (dateforeground_t) {
    persist_write_int(KEY_DATEFOREGROUND, dateforeground_t->value->int32);
  }

  if (datetimeout_t) {
    #ifdef SHOW_APP_LOGS
        APP_LOG(APP_LOG_LEVEL_DEBUG, "%ld", datetimeout_t->value->int32);
    #endif
    persist_write_int(KEY_DATETIMEOUT, datetimeout_t->value->int32);
  }

  time_t now = time(NULL);
  struct tm tick_time = *localtime(&now);
  display_time(&tick_time);
}

static void init() {
  s_main_window = window_create();
  window_set_background_color(s_main_window, GColorClear);
  window_set_window_handlers(s_main_window, (WindowHandlers) {
    .load = main_window_load,
    .unload = main_window_unload,
  });
  window_stack_push(s_main_window, true);
  tick_timer_service_subscribe(MINUTE_UNIT, tick_handler);
  accel_tap_service_subscribe(tap_handler);
  app_message_register_inbox_received(inbox_received_handler);
  app_message_open(app_message_inbox_size_maximum(), app_message_outbox_size_maximum());
}

static void deinit() {
  accel_tap_service_unsubscribe();
  tick_timer_service_unsubscribe();
  window_destroy(s_main_window);
}

int main(void) {
  init();
  app_event_loop();
  deinit();
}
